### ISSUE TITLE
OSP core and user access rights

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#178]
In GitLab by @yoavnash on Nov 21, 2019, 10:43

Should OSP-core be agnostic to the user identity and its access rights?

Pros:
- Easier to implement.

Cons:
- Problematic in Jupyter Notebooks applications

**Comment by aaronAB1993** [comment]
@yoavnash Would be great if you could leave a statement here, that issue is quite old. I think it brings us back to the question that I have in mind: Having an authentication layer? So this might be an old issue but a recent discussion.

**Comment by yoavnash** [comment]
I think we can close this, as we decided (for now) not to support user access rights.
