### ISSUE TITLE
Allow None values

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#208]
In GitLab by @urbanmatthias on Dec 11, 2019, 17:34

**Comment by urbanmatthias** [comment]
@yoavnash Why do we need this?

I would prefer not setting an attribute rather than setting it to None.

I think the main issue is that osp-core forces you to have values for all attributes on initialization, which might not be the case.

**Comment by yoavnash** [comment]
I'm not sure what was the motivation there. I will close this issue for now.
