### ISSUE TITLE
Data type for OClasses

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#212]
In GitLab by @yoavnash on Dec 13, 2019, 11:32

The motivation for this is to have a way to uniquely refer to a concept.

For example, we now have: `NS.WEIGHT(value="80", unit="kg")`. Other users might type `Kg` instead of `kg`.
To have a uniform representation, it is here proposed to use `NS.WEIGHT(value="80", unit=NS.KG)`

**Comment by urbanmatthias** [comment]
I will close this issue: 
- because it is contrary to what is allowed in OWL
- because in EMMO, the user would create a new kg-CUDS object every time he needs one (because of philosophy). This can be attached via `add()`
