### ISSUE TITLE
Suggestion: extend the one(), first() and all() API to core functions

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#215]
In GitLab by @yoavnash on Dec 18, 2019, 15:56

Would be really nice to have:
``` python
c = a.get(class=NS.B).one().get(class=NS.C).one()
```
Instead of 
``` python
c = a.get(class=NS.B)[0].get(class=NS.C)[0]
```
or
``` python
b_array = a.get(class=NS.B)
b = b_array[0]
c_array = b.get(class=NS.C)
c = c_array[0]
```

Currently only implemented in `session.load_by_oclass`

**Comment by aaronAB1993** [comment]
I looked into this. It is impossible to implement this without breaking backwards compatibility or without confusing the user too much. Reason: Right now the `cuds.get()` returns a `list`. However, the `first()`, `all()` and `one()`  for the sessions are based on a customized generator class. So when we want to implement this for the CUDS as well, we have to construct a customized class that is somewhat a generator and a list at once. Image a sitation like this:
```python
a = cuds.get()
a[12]
next(a)
```
Where is the `next` supposed to start? Also, if `get` returns such a customized class, checks like this will fail: `cuds.get() == []`, which is used a lot in our testing (and I assume also elsewhere already).

So if we want to be backwards compatible I rather suggest something like this:
```python
cuds.get(first=True)
cuds.get(one=True)
```
or
```python
cuds.get(reduction='one')
cuds.get(reduction='first')
```

Note that `cuds.get().all()` is simply `cuds.get()` already.

@yoavnash What do you think?

**Comment by aaronAB1993** [comment]
There was a remark from @urbanmatthias : The results of `get()` are unordered anyway, so it raises the question why we return a list at all and why anyone would do something like `cuds.get()[12]`. Maybe we should get rid of `list` as the return type at some point.

**Comment by urbanmatthias** [comment]
> Edit: The results are ordered when you get objects by a list of uids

Yes, that is true....

**Comment by yoavnash** [comment]
Do we necessarily want to be backward compatible? I don't think (yet) it's a must on this issue.

**Comment by urbanmatthias** [comment]
We have promised several times that the API is stable

**Comment by yoavnash** [comment]
Well, we are beta, so I think it's still ok. What about the return value of `get` that you mentioned in another discussion?

Putting aside backward compatibility just for a moment, what would be the best API for the core methods?  is it `a.get()[0]`, `a.get().first()` or `a.get(first=True)`?

**Comment by urbanmatthias** [comment]
What other discussion do you mean? The get() returns a list in almost all cases. The only exception is when you call it by a single uid, then it will be a cuds object only (e.g. to allow `b = a.get(b_uid)`).

From my point of view, `a.get().first()` is the best option if we ignore backwards compatibility, because it is consistent with the query result of load_by_oclass.

But I also think that backwards compatibility is important now.... 

The `cuds.get() == []` could be fixed by implementing the `__equals__` magic method, but probably it will still break stuff....

**Comment by yoavnash** [comment]
Sorry, I meant `add`

**Comment by urbanmatthias** [comment]
I think the add return value is unrelated. This one was about whether `a.add(b)` should return `a` or `b`

**Comment by yoavnash** [comment]
It's still a change in the API, isn't it? Anyway, I think it still might be worth it, if we are truly improving the user experience.

**Comment by urbanmatthias** [comment]
Ah, yeah but for this one we decided to leave it as it is, because it makes working with multiple sessions easier

**Comment by aaronAB1993** [comment]
I agree, ignoring compatibility it will be better to move away from return type list. So being consistent with the sessions `load_by_oclass` etc. should be the goal. Nevertheless, breaking it does not seem to be a good idea. Although if we break it, we should rather do it early than late.

**Comment by urbanmatthias** [comment]
Do you think it would be possible to have something that will mostly not break anything, e.g. by also implementing __equals__ to compare with an empty list, s.t. almost all previous code will work? Then we can print warnings e.g. when the user compares with a list, uses `[0]` to access the first element etc.

**Comment by aaronAB1993** [comment]
I could do that but there is still the open question of how to treat this case:
```python
a = cuds.get()
a[12]
next(a)
```
It is not really clear to me where the "next" should point at, when the 12ths element was accessed

**Comment by urbanmatthias** [comment]
In this case we could print a warning, that the user uses both `[12]` and `next`, or we always print a warning on `[12]`.
Depends on which features we want to support in the future.

**Comment by yoavnash** [comment]
If we could support both, I agree that that would be really great.
