### ISSUE TITLE
Should data models be queryable by SPARQL and other standard ontology tools?

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#228]
In GitLab by @yoavnash on Jan 9, 2020, 16:40

It may be relevant when the data model of an application is desired to be discoverable (by standard ontology tools such as SPARQL).

**Comment by urbanmatthias** [comment]
@yoavnash Any progress here?

**Comment by yoavnash** [comment]
Can we use an RDF/OWL file to describe constraints that come additionally to those that already appear in the ontology?

**Comment by urbanmatthias** [comment]
Yes, an OWL ontology is basically just a set of restrictions on individuals. But this would blur the lines between ontologies and  datamodels even more.

**Comment by urbanmatthias** [comment]
And it should be possible to add constraints to an already existing ontology in owl.

**Comment by yoavnash** [comment]
> But this would blur the lines between ontologies and datamodels even more.

Can you explain more? If we could have a separate OWL file for additional constraints, then this file, together with the ontology, would be called (in my view) the data model. This would solve the "tennis ball in lab" problem, and for me that would be the main advantage of having a data model.

**Comment by urbanmatthias** [comment]
> But this would blur the lines between ontologies and datamodels even more.

I mean it is already a bit difficult to understand when we use a datamodel file and when we use constraints in the ontology. But maybe it's a good thing if we use the same language for both.

But please note that in order to check if the data satisfies an owl ontology, you have to run the reasoner......

**Comment by yoavnash** [comment]
Would I a be able to run the reasoner only on a segment of the data? (i.e., a container with its content)

**Comment by urbanmatthias** [comment]
I think this should be possible. You provide the reasoner with an owl file. In that case you only have the data of that one container in the file.

**Comment by urbanmatthias** [comment]
closed and tagged for future reference.
