### ISSUE TITLE
How to enforce application-specific constraints?

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#229]
In GitLab by @yoavnash on Jan 9, 2020, 16:42

Two alternatives:
1. Modules/multiple ontologies
1. Data models

A *module* is an ontology fragment in which context-specific constraints are enforced by subclassing of classes in common ontology classes. 

A *data model* is written in a separate file in YAML format. Its main use is to enforce context-specific constraints whenever data is pushed is to the dataspace. It is not allowed to create new classes in a data model file, only to strengthen existing constraints or provide new ones.

**Comment by urbanmatthias** [comment]
Another idea: https://www.w3.org/TR/shacl/
