### ISSUE TITLE
Document the solution for solving name conflict between osp-core/pico and other packages that use the same name

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#231]
In GitLab by @yoavnash on Jan 14, 2020, 09:37

The documentation should be updated with the following information:

In order to resolve a possible name conflict between osp-core/pico and other packages that use the same name, the user should enter the full path of osp-core/pico. The path should be given in the docs.

**Comment by urbanmatthias** [comment]
It's documented in the readme to use `python -m osp.core.pico`  in that case.
