### ISSUE TITLE
Restructure CUBA

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#268]
In GitLab by @yoavnash on Mar 10, 2020, 10:40

Currently everything inherits from CUBA.ENTITY which is an oclass. This is problematic for OWL which distinguishes, for example, between an oclass and a relationship. 
It would perhaps be more logical to have CUBA.OCLASS, CUBA.ATTRIBUTE, and CUBA.RELATIONSHIP, all inherit from CUBA.ENTITY which by itself is not an oclass.

**Comment by urbanmatthias** [comment]
this has been done. we now have cuba.Class instead of cuba.Entity.
cuba.Relationship and cuba.Attribute do no longer have a superclass
