### ISSUE TITLE
thread safety for the get() method when the expired buffer is not empty

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#271]
In GitLab by @yoavnash on Mar 11, 2020, 12:06

When two threads are accessing the same session which initially had a non-empty expired buffer, then some peculiarities occur.

**Comment by kysrpex** [comment]
> In GitLab by @yoavnash on Mar 11, 2020, 12:06
> 
> When two threads are accessing the same session which initially had a non-empty expired buffer, then some peculiarities occur.

OSP-core is currently single-threaded if I am not wrong.

Do you have an specific example where this is actually a concern? I can only think of the transport session, if it is even a concern there.

**Comment by kysrpex** [comment]
@pablo-de-andres I'll close the issue until further information is provided.

**Comment by pablo-de-andres** [comment]
The issue was created by @yoavnash, my name is there because I made the migration

**Comment by kysrpex** [comment]
> The issue was created by @yoavnash, my name is there because I made the migration

Thank you for your answer. I guess he was already notified due to your mention.
