### ISSUE TITLE
Allow specification of all functional relationships in constructor, not only data attributes

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#275]
In GitLab by @urbanmatthias on Mar 16, 2020, 11:48

maybe we could specify an alias if a functional relationship is used in the constructor.

That is:
```
temperature = emmo.temperature(value=200)
temperature.add(qudt.celsius, rel=emmo.hasUnit)
```
is equivalnet to
```
temperature = emmo.temperature(value=200, hasUnit=qudt.celsius)
```
which is equivalnet to
```
temperature = emmo.temperature(value=200, unit=qudt.celsius)
```

Two different way to generate that alias automatically:

- remove "has" of "hasUnit"
- use range of hasUnit, which would be unit

In both cases the namespace will not be specified.

**Comment by urbanmatthias** [comment]
Duplicate of #416
