### ISSUE TITLE
install owl files directly

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#278]
In GitLab by @urbanmatthias on Mar 16, 2020, 17:53

**Comment by aaronAB1993** [comment]
I think this one can be closed now? @urbanmatthias

**Comment by pablo-de-andres** [comment]
AFAIK it is not merged with master yet.
But it should be doable whenever he is back.

(We should think about adding things to the docs, though).

**Comment by urbanmatthias** [comment]
yes we should merge and then this issue could be closed
