### ISSUE TITLE
Idea: allow to change in the data model the data type of a data attribute

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#282]
In GitLab by @yoavnash on Mar 25, 2020, 14:50

Another variation to #272 is to allow to specify/change the data type of a data attribute for an oclass from inside a data model. 

For example, if `value` is a data attribute, in one case it makes sense for it to be of type float (e.g., `NS.AREA(value=80.3, unit=...)` and for another case, it should be of type Boolean (e.g., `NS.BROKEN(value=True)`)

Is it possible?

**Comment by urbanmatthias** [comment]
closed and tagged for future reference.
