### ISSUE TITLE
File download should only be triggered if the users want to

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#317]
In GitLab by @abahde on Jun 4, 2020, 11:42

When I have a file CUDS object in the dataspace, I might only want to get the file object and not the file itself (i.e. trigger a download). If the user does not specify a file destination in the session context, the files are downloaded to a temp folder. Would be better to not download them at all in such a case. (Think about a very big file or many files that are not needed on the client machine but only their objects).

**Comment by aaronAB1993** [comment]
Even better would be to provide a download functionality directly on the cuds (or with a util)

download(file_cuds)

**Comment by kysrpex** [comment]
> Even better would be to provide a download functionality directly on the cuds (or with a util)
> 
> download(file_cuds)

Solved on SimPhony v4 specifically in this way.
