### ISSUE TITLE
Make pico uninstall "*" more user friendly

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#319]
In GitLab by @pablo-de-andres on Jun 5, 2020, 14:37

- Make the error for `pico uninstall *` (* is unquoted) more understandable.
- Maybe provide a keyword to used instead of "*", like `all`.

**Comment by urbanmatthias** [comment]
* is impossible, because bash will automaically replace it with all files in the current directory.
I like `all` though.

**Comment by aaronAB1993** [comment]
It is now `pico uninstall all` to uninstall all ontologies.

**Comment by pablo-de-andres** [comment]
And `"*"` is no longer supported?
Asking for the docs
