### ISSUE TITLE
Support in-depth deletion

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#323]
In GitLab by @yoavnash on Jun 9, 2020, 09:46

On top of the basic deletion functionality that was implemented (issue #309), it would be useful to have an in-depth deletion capability. That is, deleting a CUDS object and all of its content.

**Comment by urbanmatthias** [comment]
any progress here @yoavnash ?

Should @aaronAB1993 or me work on this?

**Comment by yoavnash** [comment]
I created a simple recursive function to have this functionality. However, I still haven't looked into how to solve this issue:
https://github.com/simphony/osp-core/issues/421

**Comment by urbanmatthias** [comment]
@yoavnash this issue can be closed, correct?
