### ISSUE TITLE
Similarities and differences between SimPhoNy and approaches of the Semantic Web community

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#332]
In GitLab by @urbanmatthias on Jun 17, 2020, 15:02

This issue is meant to collect similarities and differences between SimPhoNy and approaches of the Semantic Web community.
@yoavnash @abahde please comment if you want to add anything to this list.

**Comment by yoavnash** [comment]
May be relevant: https://sparqlwrapper.readthedocs.io/en/latest/index.html
