### ISSUE TITLE
Make _load_from_backend abstract

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#334]
In GitLab by @urbanmatthias on Jun 22, 2020, 10:14

**Comment by aaronAB1993** [comment]
why is that desired?

**Comment by pablo-de-andres** [comment]
Because that way developers now (and get notified) that it has to be overriden.

Otherwise it doesn't work, but they get a confusing error. The way to enforce coding it is by making it abstract

**Comment by urbanmatthias** [comment]
I think I did this at some point. I just look at the code and it is abstract. Will close the issue
