### ISSUE TITLE
Installation errors due to old version of pickle file in ~/.osp_ontologies

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#419]
Due to an old version of a pickle file in ~/.osp_ontologies, I had problems updating the version of OSP-core. I wonder if this is something that has been taken into account in the installation process.

**Comment by aaronAB1993** [comment]
@urbanmatthias  Is that one solved now due to the new way how ontologies are installed with the owl installer?

**Comment by urbanmatthias** [comment]
should be solved.
