### ISSUE TITLE
Transport Session Data Volume Information

### ISSUE THREAD

**Issue by aaronAB1993** [simphony/osp-core#426]
We found that the transport session needs quite some time to serialize a significant amount of objects. We would like to give some information on client side of how much volume (how many objects) is going to be sent and received. It helps the user to better understand what is going on. It will be helpful for some recent use cases in the DSMS, but in the future it should become relevant for everyone.

@urbanmatthias I would take care of that. Is that ok?

**Comment by urbanmatthias** [comment]
This has been dropped, correct? I'll close it.
