### ISSUE TITLE
Iterator for ontology entities

### ISSUE THREAD

**Issue by aaronAB1993** [simphony/osp-core#436]
At the moment code like this fails:
```
from osp.core.namespaces import city
city._entites
```
with: `"Unknown entity '_entities' in namespace city"`

There are still cases, where we need to iterate over the ontology entities. Would be nice to have that feature also in the current setup of the namespaces.

**Comment by urbanmatthias** [comment]
Can you try:

for entity in city:
   # do stuff

**Comment by urbanmatthias** [comment]
@aaronAB1993 did you check if this has been fixed on develop?

**Comment by aaronAB1993** [comment]
@urbanmatthias I checked. It is fixed on master as well as v.3.5.0-dev. I close this issue. Thanks!
