### ISSUE TITLE
No inverse relationship crashes transport layer

### ISSUE THREAD

**Issue by aaronAB1993** [simphony/osp-core#437]
If you have an ontology with a relationship that has no inverse defined, the instantiation fails on server side of the transport session. An example to reproduce: 

- Take the city ontology and out comment the inverse of `hasInhabitant` and `isInhabitantOf` (i.e. `hasInhabitant` has no inverse from that point on) 
- Reinstall the city ontology
- Run the unit test `python -m unittest tests/test_transport_sqlite_city.py`

Error:
```
RuntimeError("Error on Server side: %s" % data[7:])
RuntimeError: Error on Server side: KeyError: "Unknown entity 'INVERSE_OF_hasInhabitant' in namespace city. For backwards compatibility reasons we also looked for I_N_V_E_R_S_E__O_F_HAS_INHABITANT and failed."
```

**Comment by urbanmatthias** [comment]
I can reproduce
