### ISSUE TITLE
BUG: Cannot use `from osp.core.namespaces import ...` on latest version (3.3.9)

### ISSUE THREAD

**Issue by flongford** [simphony/osp-core#444]
I am using osp-core 3.3.9, built using `pip install git+https://github.com/simphony/osp-core.git@v3.3.9.dev` on macOS with a python 3.6 runtime. 

Importing the `cuba` ontology via the import statement `from osp.core.namespaces import cuba` raises an `ImportError`, though the ontology can be imported from the `osp.core.ontology` module.

Referencing user-made ontologies (example: `my_ontology`) that have been installed using `pico` also resorts in the same error, even though the traceback informs upon installation: 

`[osp.core.ontology.yml.yml_parser]: You can now use from osp.core.namespaces import my_ontology`

I noticed in the test code there appears to be a commonly used work around for this situation:

```python
try:
    from osp.core.namespaces import my_ontology
except ImportError:
    from osp.core.ontology import Parser
    from osp.core.namespaces import _namespace_registry
    Parser(_namespace_registry._graph).parse("my_ontology")
    _namespace_registry.update_namespaces()
    from osp.core.namespaces import my_ontology
```

However, running this from an ipython console for both `cuba` and `my_ontology` namespaces raises the following error:

```
File "~/<path-to-env>/lib/python3.6/site-packages/osp/core/ontology/parser.py", line 39, in parse
    with open(file_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/<path-to-env>/lib/python3.6/site-packages/osp/core/ontology/docs/my_ontology.yml'
```

Are these errors expected - i.e. is anyone able to reproduce them or is it likely due to something in my local env?

**Comment by urbanmatthias** [comment]
Hi Frank,

could you retry on the latest master branch. There was an issue with python3.6.

Cheers,

Matthias

**Comment by flongford** [comment]
Hi Matthias, I can confirm that installing from master fixes this bug - many thanks!
