### ISSUE TITLE
Make use of contexts of rdfliblib

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#454]
We use rdflib https://rdflib.readthedocs.io/en/stable/ to store the ontology.
We have one graph where all the installed ontologies are stored (osp.core.ontology.namespace_registry.NamespaceRegistry._graph).
This graph is a triplestore.

But rdflib also supports quadstores, which could improve performance when querying the ontology.
This is how I think it works:
Each graph has a store, where all the data is stored. But multiple graphs could also have the same store.
Each graph has an identifier in the form of an iri.
When you store, the fourth column (context) will store this identifier of the graph.
With that it can more efficiently distinguish which triple belong to each graph.

I think it would make sense to have multiple graphs, one for each namespace. [E.g. the get by label method could become more elegant.](https://github.com/simphony/osp-core/blob/0da7b0ce18c1db9ea7b3ef91bd3dc2dd17f1b33a/osp/core/ontology/namespace.py#L89) Currently we get all the entities with the given label (which shouldn't be many), and afterwards return only those that fit the namespace.

This issue consists of the following tasks:
- Take a look at rdflib and check how the contexts work.
- Confirm that this change makes sense.
- Implement the change: In osp.core.ontology update:
  - parser.py
  - yml.yml_parser.py
  - namespace_registry.py
  - namespace.py

**Comment by aaronAB1993** [comment]
I checked the `ConjunctiveGraph` class of `rdflib` and it is context-aware, i.e. it is possible to refer to "sub-graphs" (type `Graph`).
However, for that we would need to go through the "emmo-inferred" (https://raw.githubusercontent.com/emmo-repo/EMMO/master/emmo-inferred.owl) and check for every entity the namespace prefix to then add it to the corresponding sub-graph in `rdflib`. This is basically the same effort which is currently done at runtime to get the right entity from a namespace. This means, introducing the above change would shift this effort from runtime to installation. It is some effort to implement this and the advantage we gain is not substantial. So we close this issue. 

For future reference of conjunctive graphs:
https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.graph.ConjunctiveGraph
https://github.com/RDFLib/rdflib/blob/master/examples/conjunctive_graphs.py

@urbanmatthias please approve my comment.
