### ISSUE TITLE
Reference by label without language tag

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#517]
When reference_by_label is True and the user executes `my_namespace.my_entity`, the system will look for the label `my_entity` in `my_namespace` with language tag `en`.  This will lead to problems if the language tags are missing or in a different language.

**Comment by kysrpex** [comment]
Now the system will not care about the language tag, unless specifically instructed by using `my_namespace["my_entitity", "lang"]`. This ability to specify the language is only useful in one case: in an ontology where two different concepts have a the same name in different languages. For example "Burro" means butter in Italian but donkey in Spanish, so in that case you would refer to butter with `my_namespace["Burro", "it"]` and to donkey with `my_namespace["Burro", "es"]`.
