### ISSUE TITLE
Choose label predicate in OWL ontology

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#523]
It would be nice if in e.g. osp/core/ontology/docs/emmo.yml there would be the option to specify which label predicate should be used (e.g. skos:prefLabel or rdfs:label).

Default should be rdfs:label I think.

In the same file we could also define the language of the labels.

**Comment by urbanmatthias** [comment]
Hi @eich-2020 

#517 

When you want to reference an entity you either use dot notation or square brackets:

```py
<namespace>.<name>
<namespace>["<label>"]

# examples
city.Citizen
city["Citizen"]
```

Square brackets usually get the entities by a label, dot notation by URI (append <name> to URI of <namespace>).
In the case of emmo both get them by labels (reference_by_label is True).

Getting by label means the entity with the label in the square brackets is returned:

https://github.com/simphony/osp-core/blob/v3.5.0-dev/osp/core/ontology/namespace.py#L121-L123

As you can see from the link above I uses SKOS.prefLabel for that. The reason for this is that EMMO uses SKOS.prefLabel.
Some ontologies don't use SKOS.prefLabel, though.

I propose to either:
- First check if SKOS.prefLabel can be used and if not, use RDFS.label (super-property of SKOS.prefLabel, used very often).
- or let the user specify the label to use in the emmo.yml/foaf.yml file. E.g by parsing the yml and add a triple to the graph similar to https://github.com/simphony/osp-core/blob/v3.5.0-dev/osp/core/ontology/parser.py#L324-L338 .

**Comment by kysrpex** [comment]
I suggest to do both actually. If both can be used then use the preference in the yml file if there is any defined, otherwise fallback to SKOS.prefLabel.

**Comment by urbanmatthias** [comment]
Also an option. I updated the links in the text above.

**Comment by kysrpex** [comment]
After working in the solution, I have realized that this in fact pointless to establish a preference here. What makes sense is just to check all labels regardless of whether they are RDFS or SKOS labels, and return the object. That's what I ended up implementing.
