### ISSUE TITLE
Reduce the number of rdflib calls

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#552]
Repeated rdflib calls are slow. Much time is wasted when computing the transitive hull of rdfs:subClassOf to compute <oclass>.subclasses.

An idea to reduce the number of queries to the internal ontology rdf-graph is to precompute sth like this.

**Comment by urbanmatthias** [comment]
Two options:
  - precompute the subclasses in an ASCII file during installation --> during initialization you load the ascii
  - if user calls subclasses once during runtine, cache it

**Comment by pablo-de-andres** [comment]
I don't think the subclasses will require that much space overhead (since they act on the ontology, and not the data instances).
I think I would compute them upon installation. That way there won't be unexpected delays each time they are queried for the first time.

**Comment by urbanmatthias** [comment]
Well i think there won't be that much of a delay if you compute the subclasses once. What causes the delay is when the subclasses are computed repeadetly e.g. in a loop

**Comment by urbanmatthias** [comment]
@kysrpex so you can decide yourself what you do. You can run your own experiments etc.
