### ISSUE TITLE
Parse hasValue statements

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#554]
See https://gitlab.cc-asp.fraunhofer.de/ontology/applications/reaxpro/co2-activation/-/issues/9

@JoanaFMorgado how urgent is it for you?

**Comment by JoanaFMorgado** [comment]
Hi @urbanmatthias ,

This is not urgent. 
We are using the superclass in which specify the attribute at the wrapper level. 
It would be nice to allow the reported behavior in future for the sake of being fully compliant with EMMO but it is not urgent.

**Comment by yoavnash** [comment]
Hi @urbanmatthias, We just had a meeting with @JoanaFMorgado about UrWerk and it suddenly became important. Any estimation on how complicated would it be to solve it?

**Comment by urbanmatthias** [comment]
Rather simple I would say
