### ISSUE TITLE
Features of an ontology querying tool

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#555]
Let's discuss what things we would like to be able to query from an installed ontology. Once we agree on something, I can put it in this description to have them all in one location.

I summon @urbanmatthias @yoavnash and @aaronAB1993 to the discussion.

**Comment by pablo-de-andres** [comment]
One thing might be to query the classes connected to a given one, and the relationship between them (like a `relationship, class` iterator)

**Comment by pablo-de-andres** [comment]
- Querying the datatype of a given attribute
(this one could be used, for example, when de-serialising objects)

**Comment by yoavnash** [comment]
There is issue #443 that seems relevant here.
Also, in one of the project reports, I used the terminology _CUDS Object API_ and _CUDS Class API_, that perhaps it would be helpful to adopt:

>  #### CUDS API
> A CUDS object is provided with API that allows users to interact with the data. OSP-core defines several types of API and methods that can be used for that purpose. These are the CUDS object API, CUDS class API, and utility functions. 
> 1. __CUDS Object API__.  This API is meant for data manipulation (a.k.a., CRUD). It exposes the functions ‘add’, ‘get’, ‘remove’, ‘iterate’, and ‘update’ that allow the user to interact with semantically-transparent data items.
> 2. __CUDS Class API__. In addition to the CRUD API that is used to query the CUDS objects, an additional API is provided to query the ontology. This functionality allows users to get ontology information from inside the code. An example of such API method is ‘is_subclass_of’ that can be applied on a CUDS class to query whether it is a subclass (i.e., has the ‘is-a’ relationship in the ontology) of another class.
> 3. __Utility Functions__. Other capabilities are available by means of utility functions. These extend the basic API with generic code that is built on top of it, and useful for generic cases. For example, a recursive search within a CUDS container.

**Comment by urbanmatthias** [comment]
I close this issue because of the new .axioms property of OntologyClasses. If someone thinks we should reopen, please do.
