### ISSUE TITLE
UUID vs. IRI and DCAT import

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#594]
In SimPhoNy version 3, all CUDS objects are uniquely identified by a UUID. The standard in RDF data is the URI or IRI, which is a string that looks like a web-URL. Most of the time, these URIs do not link to resources on the web, but sometimes they do. In DCAT there is the dcat:downloadURL Property that allows the user to specify the download URL for a dataset. But the URL shall not be provided as a string and dcat:downloadURL is not a DatatypeProperty. Instead it’s an object property that links ontology individuals (CUDS). That means the download URL is an ontology individual, uniquely identified by an URI. In some sense they’re abusing the URI of this individual to represent the URL for downloading the datatset. Obviously, this conflicts with the fact that we’re using UUIDs instead, that cannot be abused in such a way.

I think there should be a way to attach real URIs to CUDS objects, potentially linking to UUIDs in the rdflib graph with owl:sameAs statements:

```
http://www.osp-core.com/cuds#<UUID> owl:sameAs http://www.some-real-url.com/linking/to/a/dataset.tar.gz
```

Then there could be an API that accesses these triples and gathers all the IRIs for a CUDS.
These kinds of triples are also added to the graph by the current `import_rdf_file` implementation.

One thing to note:
- We should probably make sure to send these triples via post() or the transport session.`

**Comment by urbanmatthias** [comment]
It might make sense to avoid creating a UUID, if the user specifies an IRI on initialization. Problem is that much code relies on CUDS having UUIDs.

**Comment by kysrpex** [comment]
Related issue #540.
