### ISSUE TITLE
Add API for accessing AnnotationProperties of Ontology Classes

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#596]
![Image Pasted at 2021-3-18 09-01](https://user-images.githubusercontent.com/42069939/111600211-76718d80-87d1-11eb-9121-fbe6ce3e7317.jpg)

Ontology developers might add a website (or similar) for instance that user can use to understand better the concepts in the ontology

**Comment by yoavnash** [comment]
We were also wondering whether it would be possible not just for classes, but also for objects. What do you think?

**Comment by urbanmatthias** [comment]
I'll create another issue for this.

**Comment by urbanmatthias** [comment]
Related to #597

**Comment by kysrpex** [comment]
Duplicate of #315.
