### ISSUE TITLE
Support reading and writing AnnotationProperties for CUDS objects

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/osp-core#597]
Allow AnnotationProperties for CUDS objects. Currently we only support DatatypeProperties (via dot notation) and ObjectProperties (via add/get).

What would your preferred way to access annotations of CUDS objects @yoavnash @JoanaFMorgado @pablo-de-andres @kysrpex ?

**Comment by urbanmatthias** [comment]
If we follow the conclustion from https://github.com/simphony/osp-core/issues/416 ,
we use add for everything and offer dot as suyntactic sugar for functional properties?

**Comment by urbanmatthias** [comment]
Related to #596

**Comment by yoavnash** [comment]
This issue is currently blocking us from using DCAT in OSP-core. Specifically the `dcterms` namespace stores some information as AnnotationProperties.
