### ISSUE TITLE
How to clone simphony

### ISSUE THREAD

**Issue by adrianrs79** [simphony/osp-core#610]
Hello! I am following the instructions in: https://simphony.readthedocs.io/en/latest/installation.html#osp-core-installation

  I am trying to clone simphony/osp-core using:
```sh
git clone git@github.com:simphony/osp-core.git
```
However, I did get the following error
```
Cloning into 'osp-core'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
 Any help? Thanks

**Comment by pablo-de-andres** [comment]
Hi @adrianrs79!
Thanks a lot for your feedback. Could you try through HTTPS?
```sh
git clone https://github.com/simphony/osp-core.git
```
The error might be because you don't have SSH keys configured

**Comment by yoavnash** [comment]
A corresponding issue was created in the docs: https://github.com/simphony/docs/issues/144

**Comment by pablo-de-andres** [comment]
For completion's sake, @adrianrs79
[GitHub's guide](https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account) on how to add keys if you wish to do it.

**Comment by adrianrs79** [comment]
Dear Pablo


Thanks a lot


Kind regards

Adrian Rubio Solis

**Comment by adrianrs79** [comment]
Hi Pablo

Just one question, if possible, any ontology I need to use in SimPhony I
need to create it for example in AiiDA, it is that right?

Or is there any another tool in SimPhony to create ontologies?


Thank you in advance

Best wishes

Adrian
