### ISSUE TITLE
Update LICENSE file

### ISSUE THREAD

**Issue by kysrpex** [simphony/osp-core#622]
The LICENSE file should be updated to match the new `LICENSE-BSD_3-Clause-template` file. I assume that the license on the docs should also be updated, as its content is exactly the same.

**Comment by kysrpex** [comment]
@pablo-de-andres @yoavnash Did any other institution actually contribute to OSP-core? Does not seem to be the case according to the commit history.

**Comment by yoavnash** [comment]
If I'm not mistaken, this is the so-called version 1 of SimPhoNy 1: https://github.com/simphony/simphony-common
My understanding is that the contributors of those project (at least) should be included

**Comment by pablo-de-andres** [comment]
Exactly. Top of my head I can think of Enthought (Didrik Pinte and others)

**Comment by yoavnash** [comment]
According to Torsten, who compared the [contributors](https://github.com/simphony/simphony-common/graphs/contributors) to the [partner list](https://www.simphony-project.eu/en/consortium.html), we should include Enthought, CIMNE, and University of Jyväskylä.

**Comment by yoavnash** [comment]
Change: have only IWM in the license and mentioned the others in the README file.
