### ISSUE TITLE
Unable to reach CUDS object

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#626]
When creating a CUDS object associated with a wrapper session, I'm unable to reach it by iteration or by export. Am I missing something?

Sample code:
```python
from osp.core.namespaces import city
from osp.wrappers.sqlite_wrapper_session import SqliteWrapperSession
from osp.core.utils import serialize_rdf_graph

uuid_to_lookup = None

with SqliteWrapperSession("test.db") as session:
    wrapper = city.CityWrapper(session=session)
    c = city.City(name="Freiburg", session=session)
    uuid_to_lookup = c.uid
    print('1', c)
    print('2', uuid_to_lookup)
    session.commit()

with SqliteWrapperSession("test.db") as session:
    wrapper = city.CityWrapper(session=session)
    for c in wrapper.iter():
        print('3', c)
    # print('4', session.load(uuid_to_lookup).one())
    serialize_rdf_graph('./test.ttl', format='turtle', session=session)
```
this produces an empty file named `test.ttl` and the following output:
```sh
1 city.City: e455f0f8-6ad2-45dc-9d83-4126b71c79d1
2 e455f0f8-6ad2-45dc-9d83-4126b71c79d1
```

When uncommenting the line `print('4', session.load(uuid_to_lookup).one())`, the following output is added:
```sh
4 city.City: e455f0f8-6ad2-45dc-9d83-4126b71c79d1
```
and the content of the file is:
```
@prefix ns1: <http://www.osp-core.com/city#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://www.osp-core.com/cuds#bfbe1cd9-5b6b-4094-a976-671224fc81d6> a ns1:City ;
    ns1:coordinates "[0, 0]"^^<http://www.osp-core.com/cuba#_datatypes/VECTOR-INT-2> ;
    ns1:name "Freiburg"^^xsd:string .
```

However, I would expect that the CUDS object will be exported even without loading it explicitly.

**Comment by pablo-de-andres** [comment]
Could this be because `serialize_rdf_graph` only looks at the registry when it should load everything from the backend?

**Comment by yoavnash** [comment]
That's what I think, but that misleads the user

**Comment by kysrpex** [comment]
> Could this be because `serialize_rdf_graph` only looks at the registry when it should load everything from the backend?

The serializer is trying to find all CUDS objects from the root of the session, the wrapper. The city was never added to the wrapper, so it is not exported.

If you add the city to the wrapper, then it will be exported.

```python
from osp.core.namespaces import city
from osp.wrappers.sqlite_wrapper_session import SqliteWrapperSession
from osp.core.utils import serialize_rdf_graph

uuid_to_lookup = None

with SqliteWrapperSession("test.db") as session:
    wrapper = city.CityWrapper(session=session)
    c = city.City(name="Freiburg", session=session)
    wrapper.add(c)
    uuid_to_lookup = c.uid
    print('1', c)
    print('2', uuid_to_lookup)
    session.commit()

with SqliteWrapperSession("test.db") as session:
    wrapper = city.CityWrapper(session=session)
    for c in wrapper.iter():
        print('3', c)
    # print('4', session.load(uuid_to_lookup).one())
    serialize_rdf_graph('./test.ttl', format='turtle', session=session)
```

_output_
```
1 city.City: 7711a5d6-159f-43b2-9821-4f1dcfbc16a5
2 7711a5d6-159f-43b2-9821-4f1dcfbc16a5
3 city.City: 7711a5d6-159f-43b2-9821-4f1dcfbc16a5
```

_test.ttl_
```
@prefix city: <http://www.osp-core.com/city#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://www.osp-core.com/cuds#7711a5d6-159f-43b2-9821-4f1dcfbc16a5> a city:City ;
    city:coordinates "[0, 0]"^^<http://www.osp-core.com/cuba#_datatypes/VECTOR-INT-2> ;
    city:name "Freiburg"^^xsd:string .
```

**Comment by yoavnash** [comment]
But then how does it make sense that adding the line `print('4', session.load(uuid_to_lookup).one())` makes the object to be exported?

**Comment by kysrpex** [comment]
> But then how does it make sense that adding the line `print('4', session.load(uuid_to_lookup).one())` makes the object to be exported?
> 
> The expected behavior of `serialize_rdf_graph('./test.ttl', format='turtle', session=session)` is that all CUDS objects of the session are exported. That is, all cuds objects in the backend.

The question that we have to ask ourselves is: does it even make sense that the city makes it to the backend in the first place?

**Comment by kysrpex** [comment]
TODO: Add a warning for unreachable objects on commit and for uncommited objects on close.
