### ISSUE TITLE
Allow installing owl ontologies without yaml configuration file

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#631]
It seems some simple ontologies can be installed without a YAML configuration file since all the necessary information appears in the ontology file itself (if info is still missing, then perhaps specifying them as arguments for `pico` makes sense). This will make ontology installation more concise.

Example:
```
identifier: my_onto
ontology_file: ./my_onto.ttl
reference_by_label: True
namespaces:
    my_onto: http://the-project.eu/my_onto#
format: turtle
```

**Comment by kysrpex** [comment]
Closing, as it is a duplicate of #541. I agree that this should be done. The command line arguments thing is a good suggestion, did not think of that.
