### ISSUE TITLE
Publish OSP-core in pypi 

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#639]
Publish OSP-core in pypi to enable easy installation of the package.

Options for the project name:
1. `pip install simphony`
2. `pip install osp-core`
3. `pip install simphony-osp-core`

Option 3 has the advantage of being able to extend for wrappers. For example: `pip install simphony-wrapper-simlammp`.

Relevent links:
- For testing: https://test.pypi.org/
- For registering: https://pypi.org/

**Comment by pablo-de-andres** [comment]
We could also use the first option and extend it for wrappers, right? `simphony` installs the core, the rest come with the prefix.
Might be simpler.

**Comment by pablo-de-andres** [comment]
[simphony](https://pypi.org/project/simphony/) is taken.
