### ISSUE TITLE
Merge CUDSTranslator-utilities into osp-core

### ISSUE THREAD

**Issue by MBueschelberger** [simphony/osp-core#651]
In order to get rid of the additional CUDSTranslator-package as an historical outlier from the FORCE-projekt, it would be great to merge the utilities from the [CUDSTranslator](https://github.com/simphony/CUDSTranslator) into osp-core. If accepted, the unittests could re-used as well.

Basically the initial goal of this package was to have a [class](https://github.com/simphony/CUDSTranslator/blob/dev/osp/wrappers/cuds_translator/cuds_translator.py) in order to import RDF-individuals from a certain file and directly retrieve the CUDS and rdflib.terms via SPARQL (file or string). The return of the query-function might ideally be a consistent 2D nested list (e.g. [[result_x1, result_y1], [result_x2, result_y2], [None, result_y3], [None, None], [result_x5, None], ...] ).

**Comment by kysrpex** [comment]
It seems that solving #655 carefully and appropriately would actually do most of what CUDSTranslator does. Therefore I'll close this issue and we will focus on #655.
