### ISSUE TITLE
Installing/importing ontologies from code

### ISSUE THREAD

**Issue by yoavnash** [simphony/osp-core#660]
[Update] In some situations, it could be useful to be able to install ontologies from the code itself, rather than installing them via pico.

**Comment by yoavnash** [comment]
No, but rather being able to do something such as:
```python
from osp.core.ontology import install_ontology

install_ontology('my_ontology.owl')
```

**Comment by yoavnash** [comment]
Is there a chance to support it before the next major version?

**Comment by kysrpex** [comment]
> Is there a chance to support it before the next major version?

You are lucky today (see #761).

**Comment by yoavnash** [comment]
Great! :)
What would be the command I should call?

**Comment by kysrpex** [comment]
> Great! :) What would be the command I should use?

It's on #761's description. Just pass paths separated by commas to `install` or package names separated by commas to `uninstall`. If you look at the commit there is an `overwrite` boolean argument for `install` just like in normal command-line `pico`. `packages` and `namespaces` do not take arguments (just like in normal command-line pico).

**Comment by yoavnash** [comment]
It's a bit hard to extract from the description. I would suggest adding a section about it somewhere in the docs.

**Comment by Ktoti** [comment]
> > Great! :) What would be the command I should use?
> 
> It's on #761's description. Just pass paths separated by commas to `install` or package names separated by commas to `uninstall`. If you look at the commit there is an `overwrite` boolean argument for `install` just like in normal command-line `pico`. `packages` and `namespaces` do not take arguments (just like in normal command-line pico).

I have some questions: Where is the description? and why do we need more than just 1 path? is the path passed the yml file path? Thanks :)

**Comment by kysrpex** [comment]
> > > Great! :) What would be the command I should use?
> > 
> > 
> > It's on #761's description. Just pass paths separated by commas to `install` or package names separated by commas to `uninstall`. If you look at the commit there is an `overwrite` boolean argument for `install` just like in normal command-line `pico`. `packages` and `namespaces` do not take arguments (just like in normal command-line pico).
> 
> I have some questions: Where is the description? and why do we need more than just 1 path? is the path passed the yml file path? Thanks :)

With description I mean [this](https://github.com/simphony/osp-core/pull/761#issue-1166347757) specific message. I will answer the other questions together with the answer to [this](https://github.com/simphony/osp-core/pull/761#issuecomment-1068948630) other message from you.
