### ISSUE TITLE
Strange behaviour of CUDS remove (DataspaceSession)

### ISSUE THREAD

**Issue by kysrpex** [simphony/osp-core#662]
Follow-up of #638. Seems to be fixed by PR #659 for sessions other than the dataspace session (and possibly the transport session)·

See [this comment](https://github.com/simphony/osp-core/pull/659#issuecomment-864089393) for more details.

**Comment by kysrpex** [comment]
> See [this comment](https://github.com/simphony/osp-core/pull/659#issuecomment-864089393) for more details.

@paulzierep I have experienced seen a similar issue in UrWerk, even after installing the fix from PR #659. It was due to the database being "contaminated" with some extra triples that were created before PR #659. However, since as far as I understand you are starting out with a new database file, this should not be the reason in your case. I'll run my own DSMS instance to debug this.

**Comment by kysrpex** [comment]
@paulzierep The PR #668 solves the issue, at least for a clean _"PRIVATE_DATASPACE_DB_NAME"_. Should be merged in the next few days.

**Comment by paulzierep** [comment]
@kysrpex great job, I will test with my DSMS set-up asap !

**Comment by yoavnash** [comment]
@paulzierep maybe you could add your response to the discussion thread in #668 to make it a bit easier to follow.
