### ISSUE TITLE
Should the tests be run as part of the docker build?

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/osp-core#718]
Currently, the Dockerfile [installs and runs tox](https://github.com/simphony/osp-core/blob/master/Dockerfile#L14).
I believe this will make the build process slower and is redundant if the CI passes on GitHub.

**Comment by kysrpex** [comment]
Yes. Moreover, GitHub's CI could be responsible for checking that the docker image can be successfully built.

**Comment by pablo-de-andres** [comment]
Good idea, might be tricky considering our actions are run inside a docker already
